OPNML='/globec/blanton/matlab';
addpath([eval('OPNML') '/opnml_matlab5'],'-end')    
path(path,'/globec/naimie/matlab_cen');
opnmlinit

% Setup for GRIDS and GRIDDIRS
 GRIDS=str2mat('bank150',...
               'g2s',...
               'g2s.5b');
 GRIDDIRS=str2mat('/globec/naimie/PHASE3/BANK150_MESH',...
           '/globec/naimie/PHASE3/G2S_MESH',...
           '/globec/naimie/PHASE3/G2S5B_MESH');
